### ISSUE TITLE
Create a notification feature

### ISSUE THREAD

**Issue by meri-nova** [Break-Into-Data/Break-Into-Data-Discord#16]
Come up with a way to notify users who have not submitted for a day. 

Consider two options: 

1) Internal Discord notifcations- Great for MVP 

Create a channel where everyone who has not submitted will be notified twice a day by tagging them together
Or send DM's( which we tried and got rate limited and banned)

2) External notifications using email or phone number or messaging platform - Great for long-term feature build

Consider asking for their email and phone number. 
Ask them which is the preferred method of communication between those two.

**Comment by thebadcoder96** [comment]
I think a channel would be a good option. But people might ignore that channel. Maybe we can @ the users who have submitted for a day on the submissions channel at the end of that day? [we probably can add logic to ignore the bots commands on the submissions page as well]

**Comment by KostyaCholak** [comment]
Our current idea is to use time-zone roles to group people. And notify them using @<role>
